#!/bin/sh
#
# Copyright (c) 2024 prozorecJP
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
#
# Script to create alternate root partition on NanoBSD system.
#
# usage:
#       create_alt_partition
#
LOGFILE="/var/log/create_alt_partition_$(date +%Y%m%d%H%M%S).log"
LOCK=/var/tmp/create.lock

die ()
{
  unlock
  echo "$@" >&2
  exit 1
}

lock ()
{
  if [ -e $LOCK ]; then
    die "There is on-going action"
  else
    touch $LOCK
  fi
}

unlock ()
{
  if [ -e $LOCK ]; then rm -f $LOCK; fi
}

(
set -e
set -x

lock

# these are logging purpose
mount
df


. /etc/nanobsd.conf

NUM=$(gpart show ${NANO_DRIVE} | egrep "\s+freebsd\s+" | wc -l)

if [ $NUM -eq 3 ]; then
  die "alternate root partition already exists."
fi

SIZE=$(gpart show ${NANO_DRIVE} | egrep "\s+3\s+freebsd\s+" | cut -w -f 3)

gpart add -t freebsd -s ${SIZE} ${NANO_DRIVE}
gpart create -s bsd ${NANO_DRIVE}${NANO_SLICE_ALTROOT}
gpart add -t freebsd-ufs -a 64k -b 64k ${NANO_DRIVE}${NANO_SLICE_ALTROOT}
newfs -U -L altrootfs /dev/${NANO_DRIVE}${NANO_ALTROOT}

unlock
) > ${LOGFILE} 2>&1

